### ISSUE TITLE
ceph-radosgw in error after deploy

### ISSUE THREAD

**Issue by marosg42** [openstack-charmers/openstack-on-lxd#31]
Observed on pike and ocata. After deploy, when all units are active, ceph-radosgw is in error, reporting 
hook failed: "identity-service-relation-changed" for keystone:identity-service

unit-radosgw.log shows
2017-12-27 17:14:19 DEBUG identity-service-relation-changed Site openstack_https_frontend already disabled
2017-12-27 17:14:19 DEBUG identity-service-relation-changed apache2.service is not active, cannot reload.
2017-12-27 17:14:19 DEBUG identity-service-relation-changed /usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py:182: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
2017-12-27 17:14:19 DEBUG identity-service-relation-changed   warnings.warn('Using keystoneclient sessions has been deprecated. '
2017-12-27 17:14:40 DEBUG identity-service-relation-changed Traceback (most recent call last):
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/identity-service-relation-changed", line 388, in <module>
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     hooks.execute(sys.argv)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/charmhelpers/core/hookenv.py", line 798, in execute
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     self._hooks[hook_name]()
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1896, in wrapped_f
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     restart_functions)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/charmhelpers/core/host.py", line 728, in restart_on_change_helper
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     r = lambda_f()
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/charmhelpers/contrib/openstack/utils.py", line 1895, in <lambda>
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     (lambda: f(*args, **kwargs)), restart_map, stopstart,
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/identity-service-relation-changed", line 233, in identity_changed
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     configure_https()
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/identity-service-relation-changed", line 377, in configure_https
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     setup_keystone_certs(CONFIGS)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 356, in _inner2_defer_if_unavailable
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return f(*args, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 496, in setup_keystone_certs
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     get_ks_ca_cert(ksclient, auth_endpoint, certs_path)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 356, in _inner2_defer_if_unavailable
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return f(*args, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 414, in get_ks_ca_cert
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     ca_cert = get_ks_cert(ksclient, auth_endpoint, 'ca')
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 356, in _inner2_defer_if_unavailable
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return f(*args, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/var/lib/juju/agents/unit-ceph-radosgw-0/charm/hooks/utils.py", line 384, in get_ks_cert
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     cert = ksclient.certificates.get_ca_certificate()
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/certificates.py", line 28, in get_ca_certificate
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     resp, body = self._client.get('/certificates/ca', authenticated=False)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 288, in get
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return self.request(url, 'GET', **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 447, in request
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 192, in request
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return self.session.request(url, method, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     return wrapped(*args, **kwargs)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed   File "/usr/lib/python2.7/dist-packages/keystoneclient/session.py", line 445, in request
2017-12-27 17:14:40 DEBUG identity-service-relation-changed     raise exceptions.from_response(resp, method, url)
2017-12-27 17:14:40 DEBUG identity-service-relation-changed keystoneauth1.exceptions.http.ServiceUnavailable: Service Unavailable (HTTP 503)
2017-12-27 17:14:40 ERROR juju.worker.uniter.operation runhook.go:113 hook "identity-service-relation-changed" failed: exit status 1

I did not find anything in keystone log

**Comment by marosg42** [comment]
Turns out it was http_proxy variable, when cleared, all works. Interesting only ceph-radosgw had a problem, it was a variable in model, all other charms were ok.
